# fly.toml app configuration file
app = 'video-craft-server'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mount]
  source = "video_craft_data"
  destination = "/app/public/uploads"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  CORS_ORIGIN = "https://video-toolbox.ponotech.net"
  MAX_FILE_SIZE = "524288000"
  FILE_RETENTION_HOURS = "24"